CREATE TABLE parcel (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
product_name VARCHAR(30) NOT NULL,
product_id INT(30) NOT NULL,
order_date INT(30) NOT NULL,
order_status VARCHAR(30) NOT NULL,
destination VARCHAR(30) NOT NULL,
order_type VARCHAR(30) NOT NULL,
phone_no VARCHAR(30) NOT NULL,
email VARCHAR(50),
reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
),

